baseURL = 'https://JaeSim.github.io'
languageCode = 'ko-kr'
title = "JaeSim's Workspace"
theme = 'hugo-book'

[params]
  BookTheme = 'auto'
  BookSection = '*'
  BookShowToC = true
  
[markup.goldmark.renderer]
  unsafe = true
