baseURL = 'https://JaeSim.github.io'
languageCode = 'ko-kr'
title = "JaeSim's Workspace"
theme = 'hugo-book'
# robots.txt
enableRobotsTXT = true
[params]
  BookTheme = 'auto'
  BookSection = '*'
  BookShowToC = true
  
[markup.goldmark.renderer]
  unsafe = true

[sitemap]
# always, hourly daily, weekly, monthly, yearly, never
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  tag = "tags"
  category = "categories"